# Generated by Django 4.1.3 on 2022-11-10 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.CharField(
                        max_length=200, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("marketplace", models.CharField(max_length=200)),
                ("purchase_date", models.DateTimeField(null=True)),
                ("currency", models.CharField(max_length=5)),
            ],
        ),
    ]
